# Generated by Django 5.1 on 2024-09-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistrationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Student Name')),
                ('mobile', models.CharField(max_length=150, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('state', models.CharField(max_length=150, verbose_name='State')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('create_at', models.DateTimeField(verbose_name='Create at')),
            ],
            options={
                'verbose_name': 'student_details',
                'verbose_name_plural': 'student_details',
                'db_table': 'student_details',
            },
        ),
    ]
