# Generated by Django 5.1 on 2024-09-03 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedetails_is_active'),
        ('students', '0002_alter_studentregistrationdetails_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationdetails',
            name='course_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.coursedetails', verbose_name='Course Details'),
        ),
    ]
