# Generated by Django 5.1 on 2024-09-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentregistrationdetails_course_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistrationdetails',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remark'),
        ),
    ]
