# Generated by Django 5.1 on 2024-09-02 15:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=150, verbose_name='Blog Title')),
                ('blog_image', models.FileField(blank=True, null=True, upload_to='blogs', verbose_name='Blog Image')),
                ('blog_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Blog Content')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'blog_details',
                'verbose_name_plural': 'blog_details',
                'db_table': 'blog_details',
            },
        ),
    ]
