# Generated by Django 5.1 on 2024-09-02 13:22

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'course_category',
                'verbose_name_plural': 'course_category',
                'db_table': 'course_category',
            },
        ),
        migrations.CreateModel(
            name='CourseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=150, verbose_name='Course Title')),
                ('course_image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Course Image')),
                ('course_content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course Content')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.coursecategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'course_details',
                'verbose_name_plural': 'course_details',
                'db_table': 'course_details',
            },
        ),
    ]
