# Generated by Django 5.1 on 2024-09-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetails',
            name='course_image',
            field=models.FileField(blank=True, null=True, upload_to='courses', verbose_name='Course Image'),
        ),
    ]
