# Generated by Django 5.1 on 2024-09-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursedetails_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
