# Generated by Django 5.1 on 2024-09-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursedetails_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='course_url',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='URL'),
        ),
    ]
