# Generated by Django 5.1 on 2024-09-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursedetails_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetails',
            name='seo_description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='SEO Description'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='seo_keywords',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='SEO Keywords'),
        ),
        migrations.AddField(
            model_name='coursedetails',
            name='seo_title',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='SEO Title'),
        ),
    ]
